## Assignment 4: Logistic Regression and Gradient Descent


## Question 1. 

In [14]:
import numpy as np
import pandas as pd
import csv
import math

# Reading from train file
with open('LRTrain.csv', 'r', newline='') as LRTrain:
    reader = csv.reader(LRTrain)

df = pd.read_csv("LRTrain.csv")
df = df.dropna()

# Separating independent and dependent variables
x = df.iloc[:, :30]
y = df.iloc[:, 30]

# Standardizing x 
x = (x - x.mean())/x.std()

# Re-shaping y
y = y.values.reshape(y.shape[0],1)

#Reading from test file

with open('LRTest.csv', 'r', newline='') as LRTest:
    reader = csv.reader(LRTest)

df_test = pd.read_csv("LRTest.csv")
df_test = df_test.dropna()

#Separating features and diagnosis

x_test = df_test.iloc[:, :30]
y_test = df_test.iloc[:, 30]

# Standardizing x 
x_test = (x_test - x_test.mean())/x_test.std()

# Reshaping y
y_test = y_test.values.reshape(y_test.shape[0],1)

In [41]:
def gradient_descent(w,x,y):
    
    n = x.shape[0]
        
    mul = np.dot(x,w)
    ypred = 1/(1+np.exp(-mul))
    cost = -np.sum(y*np.log(ypred) - (1-y)*np.log(1-ypred))/n     
    dif = mul - y
    gradient  = np.dot(np.transpose(x),dif)/n
    
    return gradient,cost,ypred

In [42]:
def logistic_reg(w,X,Y,gamma,steps):
   

    costs = []
    
    for i in range(steps):
        
        gradient, cost,ypred = gradient_descent(w,X,Y)
        w  = w - gamma*gradient
        
        if(i%100==0):
            costs.append(cost)
            
    return w,gradient,costs

In [38]:
w = np.zeros((x.shape[1],1))

w,gradient,costs = logistic_reg(w,x,y,0.00001,2000)
print(f' Trial 1: {np.linalg.norm(costs)}')
print(w)
w2,gradient2,costs2 = logistic_reg(w,x,y,0.0001,2000)
print(f' Trial 2: {np.linalg.norm(costs2)}')

w3,gradient3,costs3 = logistic_reg(w,x,y,0.0005,1500)
print(f' Trial 3: {np.linalg.norm(costs3)}')

w4,gradient4,costs4 = logistic_reg(w,x,y,0.001,2000)
print(f' Trial 4: {np.linalg.norm(costs4)}')

w5,gradient5,costs5 = logistic_reg(w,x,y,0.00005,1500)
print(f' Trial 5: {np.linalg.norm(costs5)}')

 Trial 1: 0.7435100885520322
[[ 6.25287654e-03]
 [ 2.83592727e-03]
 [ 6.35472705e-03]
 [ 6.05226075e-03]
 [ 3.28137322e-03]
 [ 4.90946445e-03]
 [ 5.72008656e-03]
 [ 6.63102260e-03]
 [ 2.55726591e-03]
 [-4.37665074e-04]
 [ 4.81163179e-03]
 [-7.95763463e-04]
 [ 4.82378245e-03]
 [ 4.56741585e-03]
 [-3.70933615e-04]
 [ 2.00360679e-03]
 [ 1.85675993e-03]
 [ 3.36406146e-03]
 [-2.09145404e-04]
 [-9.41681822e-05]
 [ 6.68195864e-03]
 [ 3.23677264e-03]
 [ 6.76025192e-03]
 [ 6.24146076e-03]
 [ 3.79020132e-03]
 [ 5.05559039e-03]
 [ 5.73972041e-03]
 [ 6.83356131e-03]
 [ 3.52106816e-03]
 [ 2.41732758e-03]]
 Trial 2: 0.7300883864905574
 Trial 3: 0.6258994860126317
 Trial 4: 0.721091509293773
 Trial 5: 0.6384423092454864


It seems like the lowest cost was in Trial 3. 

In [60]:
#Values chosen
wbest,gradient,costs = logistic_reg(w,x,y,0.00999,2000)
print('Best Value: ' ,np.linalg.norm(costs))

TypeError: unsupported operand type(s) for *: 'float' and 'dict'

## Question 2. 

In [6]:
def metrics(y_pred, y_test):
    t = len(y_test)
    
    tp  = 0
    p = 0
    fp = 0
    n = 0
    
    for i in range(t):
        if y_pred[i] == 1 and y_test[i]==1:
            tp += 1
    
    for i in range(t):
        if y_test[i] == 1:
            p += 1

    for i in range(t):
        if y_pred[i] == 1 and y_test[i]==0:
            fp += 1
    
    for i in range(t):
        if y_test[i] == 0:
            n += 1
    
    tpr = tp/p
    fpr = fp/n
    tnr = 1 - fpr
    fnr = 1 - tpr
    
    return(tpr, fpr, tnr, fnr)

In [39]:
ypred = gradient_descent(wbest,x,y)

In [43]:
ypred

(array([[-0.00359748],
        [-0.00517422],
        [-0.00181491],
        [ 0.00556865],
        [-0.00133835],
        [ 0.01018863],
        [ 0.00548764],
        [-0.0059605 ],
        [ 0.00599031],
        [ 0.01221758],
        [-0.00047365],
        [-0.00242208],
        [ 0.00624872],
        [ 0.02251898],
        [-0.01799287],
        [ 0.01366594],
        [ 0.01108231],
        [-0.00438037],
        [-0.0016134 ],
        [ 0.00667886],
        [-0.00888156],
        [-0.01069891],
        [-0.00657028],
        [ 0.00549895],
        [-0.01438851],
        [-0.00378051],
        [-0.00335214],
        [-0.01309826],
        [-0.00979916],
        [-0.01007979]]),
 -0.1607719168337483,
 array([[-0.43252333],
        [-0.52416072],
        [-0.48036468],
        [-0.57501747],
        [-0.4416985 ],
        [-0.45621302],
        [-0.57357726],
        [-0.45403487],
        [-0.45386697],
        [-0.65718   ],
        [-0.6025878 ],
        [-0.46707973],
        [-

In [7]:
def predict(x_test,ytest):
    
    y_pred =[]

    n = len(y_test)

    for i in range(n):

            y_pred.append(1/(1 + np.exp(-np.dot(np.transpose(x_test.loc[i]),wbest))))
            
            y_pred[i] = y_pred[i][0]
    return y_pred
y_pred = predict(x_test,y_test)
y_pred = np.round(y_pred)


#Performance metrics for this value of gamma

tpr, fpr, tnr, fnr = metrics(y_pred, y_test)

print(f'True Positive Rate for Model 3: {tpr}')
print(f'False Positive Rate for Model 3: {fpr}')
print(f'True Negative Rate for Model 3: {tnr}')
print(f'False Negative Rate for Model 3: {fnr}')

True Positive Rate for Model 3: 0.9693877551020408
False Positive Rate for Model 3: 0.04093567251461988
True Negative Rate for Model 3: 0.9590643274853801
False Negative Rate for Model 3: 0.030612244897959218


In [8]:
threshold = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]
print(f'  t   | TPR   | FPR   | TNR   | FNR  |')
for i in threshold: 

    y_pred = predict(x_test,y_test)
    
    for j in range(len(y_pred)):
        
        if y_pred[j] >= i:
            y_pred[j] = 1
        else:
            y_pred[j] = 0 
    tpr, fpr, tnr, fnr = metrics(y_pred, y_test)
    print(f' {i}  | {tpr:.2f}  | {fpr:.2f}  | {tnr:.2f}  | {fnr:.2f} |\n')

  t   | TPR   | FPR   | TNR   | FNR  |
 0.1  | 1.00  | 1.00  | 0.00  | 0.00 |

 0.2  | 1.00  | 1.00  | 0.00  | 0.00 |

 0.3  | 1.00  | 1.00  | 0.00  | 0.00 |

 0.4  | 1.00  | 0.80  | 0.20  | 0.00 |

 0.5  | 0.97  | 0.04  | 0.96  | 0.03 |

 0.6  | 0.50  | 0.00  | 1.00  | 0.50 |

 0.7  | 0.09  | 0.00  | 1.00  | 0.91 |

 0.8  | 0.00  | 0.00  | 1.00  | 1.00 |

 0.9  | 0.00  | 0.00  | 1.00  | 1.00 |

